### ISSUE TITLE
Race condition when multiple threads close/truncate the file

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlo_13#6]
Noticed this issue with k8s_01 inside minikube while running benchmarks

```sh
[INFO] Running com.teragrep.rlo_13.ManualRaceConditionTest
[Thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Starting writer thread
[Thread-2] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Starting truncator thread
Exception in thread "pool-1-thread-1" java.lang.RuntimeException: Got an unexpected message: >>>STARTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXEND
<<<, size 3274205
        at com.teragrep.rlo_13.ManualRaceConditionTest.lambda$null$0(ManualRaceConditionTest.java:49)
        at com.teragrep.rlo_13.MonitoredFileConsumer.readFile(MonitoredFileConsumer.java:95)
        at com.teragrep.rlo_13.MonitoredFileConsumer.accept(MonitoredFileConsumer.java:138)
        at com.teragrep.rlo_13.MonitoredFileConsumer.accept(MonitoredFileConsumer.java:32)
        at com.teragrep.rlo_12.FileTask.run(FileTask.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

Size is VERY wrong. It should be 10009 (START + 1000*X + END). Example test to reproduce the problem in 
https://github.com/StrongestNumber9/rlo_13/blob/manualtest/src/test/java/com/teragrep/rlo_13/ManualRaceConditionTest.java

And running it with 
```sh
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk mvn -DrunManualRaceConditionTest=true clean package
```

Modified test with longer delay between cleanups that only prints when getting unexpected event sizes:

```sh
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 32226451
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 49524747
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 99290645
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 95018539
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 150235055
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 30004633
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 47967860
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 88954449
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 113533689
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 73353291
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 87377382
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 35885085
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 109490626
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 154724096
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 843291930
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 21436205
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 23336152
[pool-1-thread-1] INFO com.teragrep.rlo_13.ManualRaceConditionTest - Got an unexpected message size of 43226569
```

**Comment by kortemik** [comment]
Very likely that a reader is active and new file comes in with a racy
statestore update. Need to check for this. It is not truncation in the code
but file replacement.

ke 24. toukok. 2023 klo 21.11 Strongest Number 9 ***@***.***>
kirjoitti:

**Comment by kortemik** [comment]
this is a false positive. the file is a spare file with such truncation and contains nulls between the last access and truncated start. we can try to manage this with checking for nulls but it will remove the possibility to handle binary files in case we want that.

i think we should create two different configurations of rlo_13, one that supports truncation and one that is supports binary processing.

**Comment by kortemik** [comment]
please create separate issues for both and mark this as closed.

**Comment by StrongestNumber9** [comment]
Made tickets for them #7 #8
